name: Test
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install pnpm -g
      - run: pnpm install --frozen-lockfile
      - run: npx --no-install jest --ci --coverage
